const supabase = require('./services/supabaseClient');
const fs = require('fs');
const path = require('path');

// Random lists for generating reports
const firstNames = ['Aarav', 'Vihaan', 'Aditya', 'Sai', 'Arjun', 'Rohan', 'Neha', 'Priya', 'Ananya', 'Riya', 'Amit', 'Sunil', 'Vijay', 'Rajesh', 'Suresh', 'Vikram'];
const lastNames = ['Sharma', 'Verma', 'Singh', 'Yadav', 'Gupta', 'Kumar', 'Patel', 'Joshi', 'Mishra', 'Trivedi', 'Pandey', 'Nair'];

const scamDomains = [
    'booking-ayodhya-ramayana.com',
    'ayodhyastay-offers.net',
    'ramjanmabhoomihotels.org',
    'saryu-river-retreats.in',
    'ayodhya-darshan-suites.co.in',
    'cheap-ayodhya-stay.com',
    'online-room-booking-ayodhya.net',
    'hanumangarhi-dharmshala.org',
    'ramayana-palace-verification.in',
    'sacred-stay-ayodhya.com'
];

const subpages = [
    '/rooms',
    '/book-now',
    '/special-discount',
    '/pay-advance',
    '/vip-darshan-pass',
    '/confirm-booking'
];

const descriptions = [
    'Received a WhatsApp message claiming 50% discount on rooms. Asked to make payment via direct UPI QR code.',
    'This website is a direct clone of the official Ramayana Hotel booking page. Rates are unusually low.',
    'They requested full advance payment for booking. When asked for police verification, they blocked me.',
    'Direct payment link sent via WhatsApp chat claiming to be the manager of the guest house.',
    'Website asking for credit card details and OTP on unsecure page to confirm spot booking.',
    'Fake hotel booking aggregator page offering heavy discounts on all premium Ayodhya hotels.',
    'Pilgrim group defrauded of ₹15,000 via this booking portal. No booking receipt generated.',
    'Suspicious domain demanding immediate UPI transfer for a deluxe suite near Ram Janmabhoomi.',
    'Clone booking site with fake phone numbers. Does not match official hotel website list.',
    'Demanding advance token money to secure room for VIP Darshan dates.'
];

async function seedReports() {
    console.log('--- Starting Crowdsourced Reports Seeding (50 Entries) ---');

    try {
        const reportsToInsert = [];
        const baseTime = Date.now();

        for (let i = 1; i <= 50; i++) {
            const isAnonymous = Math.random() < 0.3;
            const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
            const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
            const reporterName = isAnonymous ? 'Anonymous' : `${firstName} ${lastName}`;

            const scamDomain = scamDomains[Math.floor(Math.random() * scamDomains.length)];
            const subpage = subpages[Math.floor(Math.random() * subpages.length)];
            const reportedUrl = `https://${i}-${scamDomain}${subpage}`;

            const description = descriptions[Math.floor(Math.random() * descriptions.length)];
            const status = Math.random() < 0.4 ? 'Reviewed' : 'Pending';

            // Submit dates spread across last 10 days
            const submittedAt = new Date(baseTime - Math.floor(Math.random() * 10 * 24 * 3600 * 1000)).toISOString();

            reportsToInsert.push({
                id: `p_dummy_${i}`,
                reporter_name: reporterName,
                reported_url: reportedUrl,
                description: description,
                status: status,
                submitted_at: submittedAt,
                created_at: submittedAt,
                detected_on: submittedAt
            });
        }

        // 1. Insert into Supabase
        console.log('Inserting 50 dummy reports into real Supabase public_reports...');
        const { data: insertedSupabase, error: err } = await supabase
            .from('public_reports')
            .insert(reportsToInsert.map(r => {
                const { id, ...rest } = r; // exclude dummy string id for autogenerated uuid
                return rest;
            }))
            .select('id');

        if (err) {
            console.warn('Supabase DB Insert Warning (might be offline or mocked):', err.message);
        } else {
            console.log(`Successfully seeded ${insertedSupabase ? insertedSupabase.length : 0} reports in real Supabase.`);
        }

        // 2. Insert into local db.json file
        const dbPath = path.join(__dirname, '..', '..', 'database', 'db.json');
        if (fs.existsSync(dbPath)) {
            console.log('Found local db.json database. Appending mock reports...');
            try {
                const fileContent = fs.readFileSync(dbPath, 'utf8');
                const db = JSON.parse(fileContent);
                if (!db.public_reports) db.public_reports = [];

                // Remove previous dummy insertions if any to prevent duplicates
                db.public_reports = db.public_reports.filter(r => !r.id.startsWith('p_dummy_'));

                // Append
                db.public_reports.push(...reportsToInsert);

                fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
                console.log('Successfully appended 50 mock reports to database/db.json.');
            } catch (fileErr) {
                console.error('Error modifying database/db.json:', fileErr);
            }
        } else {
            console.log('database/db.json not found at:', dbPath);
        }

        console.log('--- Crowdsourced Reports Seeding Completed ---');
    } catch (e) {
        console.error('An unexpected error occurred during reports seeding:', e);
    }
}

seedReports();
