const supabase = require('./services/supabaseClient');
const fs = require('fs');
const path = require('path');

// List of typical Ayodhya accommodation brands
const brands = [
  'Ramayana', 'Saryu Riverside', 'Ayodhya Divine', 'Hanuman Garhi', 'Janaki', 
  'Saket', 'Guptar Ghat', 'Kanak Bhawan', 'Nandigram', 'Oudh Heritage',
  'Shri Ram', 'Mithila', 'Raghav', 'Surya', 'Triveni', 'Panchavati'
];

const suffixes = [
  'Inn', 'Palace', 'Resort', 'Suites', 'Residency', 'Grand', 'Lodge', 
  'Bhavan', 'Retreat', 'Stay', 'Heritage', 'Manor'
];

const statuses = ['Active', 'Pending Verification', 'Suspended'];

async function runSeed() {
  console.log('--- Starting Database Seeding ---');

  try {
    // 1. Fetch or create system users to satisfy thana_id foreign key constraint
    let { data: users, error: uErr } = await supabase
      .from('system_users')
      .select('id, thana_name, role');

    const defaultUsersList = [
      { id: 'u1', thana_name: 'Kotwali Nagar', nic_email: 'sho-kotnagar.ay@up.gov.in', cug_mobile: '9454403303', role: 'thana_user', is_active: true },
      { id: 'u2', thana_name: 'Kotwali Cantt', nic_email: 'sho-cantt.ay@up.gov.in', cug_mobile: '9454403298', role: 'thana_user', is_active: true },
      { id: 'u4', thana_name: 'Kotwali Ayodhya', nic_email: 'sho-kotayodhya.ay@up.gov.in', cug_mobile: '9454403296', role: 'thana_user', is_active: true },
      { id: 'u5', thana_name: 'Ram Janm Bhoomi', nic_email: 'sho-rjb.ay@up.gov.in', cug_mobile: '9454403310', role: 'thana_user', is_active: true }
    ];

    if (uErr) {
      console.warn('Warning: Could not fetch system users from real Supabase (using default users):', uErr.message);
      users = defaultUsersList;
    }

    if (!users || users.length === 0) {
      console.log('No system users found on Supabase. Seeding default police/admin users first...');
      const { data: insertedUsers, error: insErr } = await supabase
        .from('system_users')
        .insert(defaultUsersList.map(u => ({
          thana_name: u.thana_name,
          nic_email: u.nic_email,
          cug_mobile: u.cug_mobile,
          role: u.role,
          is_active: u.is_active
        })))
        .select('id, thana_name, role');

      if (insErr) {
        console.error('Failed to seed default system users on Supabase:', insErr);
        users = defaultUsersList;
      } else {
        users = insertedUsers;
      }
    }

    // Filter thana users to associate hotels with
    const thanaUsers = users.filter(u => u.role === 'thana_user');
    const fallbackUser = users[0] || defaultUsersList[0];

    console.log(`Associating dummy hotels with ${thanaUsers.length || defaultUsersList.length} available thana stations...`);

    // 2. Generate 50 unique hotels
    const hotelsToInsert = [];
    for (let i = 1; i <= 50; i++) {
      const brand = brands[Math.floor(Math.random() * brands.length)];
      const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
      const hotelName = `${brand} ${suffix} (${i})`;
      
      const cleanName = hotelName.toLowerCase().replace(/[^a-z0-9]/g, '');
      const officialUrl = `https://${cleanName}.safestay.in`;
      const email = `bookings@${cleanName}.in`;
      
      const mobileNumber = `+91 ${9000000000 + Math.floor(Math.random() * 99999999)}`;
      const gstNumber = `09AAACH${1000 + i}F1Z${Math.floor(Math.random() * 9)}`;
      const policeVerification = `PV-2026-AY-${1000 + i}`;
      
      // Select thana id randomly
      const associatedThana = thanaUsers.length > 0 
        ? thanaUsers[Math.floor(Math.random() * thanaUsers.length)] 
        : fallbackUser;
      
      const status = statuses[Math.floor(Math.random() * statuses.length)];

      hotelsToInsert.push({
        id: `h_dummy_${i}`,
        hotel_name: hotelName,
        official_url: officialUrl,
        email: email,
        whatsapp_number: mobileNumber,
        gst_number: gstNumber,
        police_verification: policeVerification,
        thana_id: associatedThana.id,
        status: status
      });
    }

    // 3. Batch insert to real Supabase
    console.log(`Inserting 50 dummy hotel entries into real Supabase verified_hotels...`);
    const { data: insertedHotels, error: hErr } = await supabase
      .from('verified_hotels')
      .insert(hotelsToInsert.map(h => {
        const { id, ...rest } = h; // exclude dummy string id for autogenerated uuid
        return rest;
      }))
      .select('id, hotel_name');

    if (hErr) {
      console.warn('Supabase DB Insert Warning (might be offline or mocked):', hErr.message);
    } else {
      console.log(`Successfully seeded ${insertedHotels ? insertedHotels.length : 0} hotels in real Supabase.`);
    }

    // 4. Batch insert to local db.json file
    const dbPath = path.join(__dirname, '..', '..', 'database', 'db.json');
    if (fs.existsSync(dbPath)) {
      console.log('Found local db.json database. Appending mock hotels...');
      try {
        const fileContent = fs.readFileSync(dbPath, 'utf8');
        const db = JSON.parse(fileContent);
        if (!db.verified_hotels) db.verified_hotels = [];
        
        // Remove previous dummy insertions if any to prevent duplicates on multiple runs
        db.verified_hotels = db.verified_hotels.filter(h => !h.id.startsWith('h_dummy_'));
        
        // Append
        db.verified_hotels.push(...hotelsToInsert);
        
        fs.writeFileSync(dbPath, JSON.stringify(db, null, 2), 'utf8');
        console.log(`Successfully appended 50 mock hotels to database/db.json.`);
      } catch (err) {
        console.error('Error modifying database/db.json:', err);
      }
    } else {
      console.log('database/db.json not found at:', dbPath);
    }

    console.log(`--- Seeding Completed Successfully ---`);
  } catch (err) {
    console.error('An unexpected error occurred during database seeding:', err);
  }
}

runSeed();
